### ISSUE TITLE
KeyError when run the example in rayflare

### ISSUE THREAD

**Issue by zainawhen** [qpv-research-group/rayflare#13]
@ phoebe,   Hello
When I run the examples program in rayFlare on ubuntu , there always report errors:
 "/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
KeyError: 'Verbosity' "
What is the problem?   thank you!

**Comment by jrd4466** [comment]
@phoebe-p , I am also running into the same issue (KeyError: 'Verbosity') when trying to run the example RCWA script with gratings list with a thinned GaAs absorber. It appears to come from the line 'RAT = S4_setup.calculate(options)'

I have been successful using ray-tracing/TMM lookup tables to generate RAT profiles in other examples that you've provided. Any ideas how to fix this for rcwa using S4? I am using a Macbook as well.

Thank you!

**Comment by phoebe-p** [comment]
Hi both, also @zainawhen apologies for the extremely late reply, I somehow missed that you had opened this issue! This is due to a change I made a while back making it possible to pass the 'verbosity' option to S4, which accidentally broke some old code. I'm sorry, I actually did not know anyone else was currently using this code (though I am very happy to see that you are!) I will correct the examples and push the correct version asap and comment again when I have done this!

**Comment by phoebe-p** [comment]
Should be fixed by commit dd616293dee48a670e36e8fa4800aab725847921

**Comment by zainawhen** [comment]
Thank you very much!







--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Phoebe Pearce  ***@***.***>
 

 
 发送时间: 2021-03-09 01:45:02
 

 
 收件人:qpv-research-group/rayflare ***@***.***> 

 
 抄送:13813929480 ***@***.***>,Mention ***@***.***> 

 
 主题: Re: [qpv-research-group/rayflare] KeyError when run the example inrayflare (#13)
 





 Should be fixed by commit dd61629
